backend:
  name: git-gateway
  repo: DACGitHub/continuasolutions.com # Path to your Github repository
  branch: collaborations # Branch to update
media_folder: "static/images"
public_folder: "/images/"
site_id: www.continuasolutions.com
collections:
  # - name: "slider" # Used in routes, e.g., /admin/collections/blog
  #   label: "Slider" # Used in the UI
  #   folder: "content/slider" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter 
  #     - {label: "Title ( not used )", name: "title", widget: "string"}
  #     - {label: "Order", name: "order", widget: "number"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Draft", name: "draft", widget: "boolean", default: false}
  #     - {label: "Exclude from Sitemap", name: "excludeFromSiteMap", widget: "hidden", default: true} 
  #     - {label: "Heading", name: "heading", widget: "string", required: false}
  #     - {label: "Sub Heading", name: "subheading", widget: "string", required: false}
  #     - {label: "Image", name: "image", widget: "image"}
  #     - {label: "Thumbnail", name: "thumbnail", widget: "image"} 
  # - name: "team" # Used in routes, e.g., /admin/collections/blog
  #   label: "Team" # Used in the UI
  #   folder: "content/team" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   editor:
  #     preview: false 
  #   fields: # The fields for each document, usually in front matter   
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Draft", name: "draft", widget: "boolean", default: false}
  #     - {label: "Name", name: "name", widget: "string"}
  #     - {label: "Degree Letters", name: "degreeletters", widget: "string", required: false}
  #     - {label: "Job Title", name: "jobtitle", widget: "string", required: false}
  #     - {label: "Image", name: "image", widget: "image"}
  #     - {label: "Thumbnail", name: "thumbnail", widget: "image"}
  #     - {label: "Blurb", name: "blurb", widget: "string"}
  #     - {label: "Body", name: "body", widget: "markdown"}  
  # - name: "news" # Used in routes, e.g., /admin/collections/blog
  #   label: "News" # Used in the UI
  #   folder: "content/news" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter      
  #     - {label: "Title", name: "title", widget: "string", required: false}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Draft", name: "draft", widget: "boolean", default: false}
  #     - {label: "Featured Image", name: "image", widget: "image", required: false}
  #     - {label: "Image 1", name: "image1", widget: "image", required: false}
  #     - {label: "Image 1 Caption", name: "image1caption", widget: "string", required: false}
  #     - {label: "Image 2", name: "image2", widget: "image", required: false}
  #     - {label: "Image 2 Caption", name: "image2caption", widget: "string", required: false}
  #     - {label: "Image 3", name: "image3", widget: "image", required: false}
  #     - {label: "Image 3 Caption", name: "image3caption", widget: "string", required: false}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "collaborations" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Collaborations" # Used in the UI
    folder: "content/collaborations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter      
      - {label: "Title", name: "title", widget: "string", required: false}
      - label: "Company"
        name: "company"
        widget: "object"
        fields:
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false}
          - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - label: "Featured Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "image"}
      - label: "Company Logo"
        name: "companyLogo"
        widget: "object"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "image"}
      - label: "Images"
        name: "images"
        minimize_collapsed: true
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Feedback"
        name: "feedback"
        widget: "object"
        fields:
          - {label: "Feedback", name: "feedback", widget: "markdown"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Position", name: "position", widget: "string"}

  - name: "clients" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Clients" # Used in the UI
    folder: "content/clients" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Job Title", name: "jobtitle", widget: "string", required: false}
      - {label: "Project", name: "project", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}              
      - {label: "Exclude from Sitemap", name: "excludeFromSiteMap", widget: "hidden", default: true} 